name: rq-lead-enricher
region: nyc

# Main Next.js Web Application
services:
  - name: web
    github:
      repo: ProvanceMedia/rq-lead-enricher
      branch: main
      deploy_on_push: true

    build_command: npm install && npm run build
    run_command: npm start

    environment_slug: node-js
    instance_size_slug: basic-xxs
    instance_count: 1

    http_port: 3000

    health_check:
      http_path: /

    routes:
      - path: /

    envs:
      - key: NODE_ENV
        value: production
      - key: NODE_TLS_REJECT_UNAUTHORIZED
        value: "0"
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: APOLLO_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: HUBSPOT_ACCESS_TOKEN
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: FIRECRAWL_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: ANTHROPIC_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET

# Discovery Cron Worker (runs continuously with scheduled cron)
workers:
  - name: discovery-cron
    github:
      repo: ProvanceMedia/rq-lead-enricher
      branch: main
      deploy_on_push: true

    build_command: npm install
    run_command: npm run discover

    environment_slug: node-js
    instance_size_slug: basic-xxs
    instance_count: 1

    envs:
      - key: NODE_ENV
        value: production
      - key: NODE_TLS_REJECT_UNAUTHORIZED
        value: "0"
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: APOLLO_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: HUBSPOT_ACCESS_TOKEN
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: ANTHROPIC_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: FIRECRAWL_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET

  # Autopilot Enrichment Worker (runs continuously with scheduled cron)
  - name: autopilot-cron
    github:
      repo: ProvanceMedia/rq-lead-enricher
      branch: main
      deploy_on_push: true

    build_command: npm install
    run_command: npm run autopilot

    environment_slug: node-js
    instance_size_slug: basic-xxs
    instance_count: 1

    envs:
      - key: NODE_ENV
        value: production
      - key: NODE_TLS_REJECT_UNAUTHORIZED
        value: "0"
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: APOLLO_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: HUBSPOT_ACCESS_TOKEN
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: ANTHROPIC_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: FIRECRAWL_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET

# Database Migration Job (runs before each deployment)
jobs:
  - name: migrate
    github:
      repo: ProvanceMedia/rq-lead-enricher
      branch: main
      deploy_on_push: true

    build_command: npm install
    run_command: npm run db:migrate

    environment_slug: node-js
    instance_size_slug: basic-xxs

    kind: PRE_DEPLOY

    envs:
      - key: NODE_TLS_REJECT_UNAUTHORIZED
        value: "0"
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET

# Note: Configure DATABASE_URL as a SECRET environment variable in DigitalOcean console
# pointing to your PostgreSQL database with SSL enabled (sslmode=require)
